name: telemed_erawan
description: "telemedErawan Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Modules
  commons:
    path: "./commons"
  components:
    path: "./components"
  domain:
    path: "./domain"

  # Features
  authentication:
    path: "./features/authentication"
  ambulance:
    path: "./features/ambulance"
  hospital:
    path: "./features/hospital"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Light-300.ttf
          weight: 300
        - asset: assets/fonts/NotoSansThai-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/NotoSansThai-Medium-500.ttf
          weight: 500
        - asset: assets/fonts/NotoSansThai-SemiBold-600.ttf
          weight: 600

  assets:
    - assets/icons/
    - assets/images/

  uses-material-design: true
