name: commons
description: Commons Module
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  flutter_localization: ^0.1.13
  intl: ^0.18.1
  intl_utils: ^2.8.6
  flutter_svg: ^2.0.9

  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: false

flutter_intl:
  enabled: true
  main_locale: th